### ISSUE TITLE
Question/Suggestion - Not an issue.

### ISSUE THREAD

**Issue by SimonBechS** [Virgula0/LeakerSearcher#1]
Hello Virgula0!

Nice tool, I've had my fair share of good shit coming from the tool.

Nevertheless, if you'd be able to make it so you can 'import' the search stringS< and it then export the found data, I believe the software would be far more intellectual - Not to mention, it stops when it finds something that matches the searched string, couldn't it be made so it searches through the entirety of the DBs and then outputs/exports everything found?

**Comment by Virgula0** [comment]
Already solved this. Will be released with the 0.2 that search in the file/s until the finish for more strings.. File export function will be introduced in next versions....
I'm going to release this evening...

**Comment by Virgula0** [comment]
Project has been updated 
closed #1
