### ISSUE TITLE
Suggestion - Non extension mode

### ISSUE THREAD

**Issue by skupfer** [Virgula0/LeakerSearcher#2]
Hi there, it would be great if it could be used on files without an extension. I got a huge dump which I want to check but none of the files got an extension. I could add them, but couldn't seed anymore then.

**Comment by Virgula0** [comment]
You can manually change extensions, an extension is important for some checks in the program so i can't remove it....
But i'll add a 5th function that is able to convert all none extensions of specified files to .txt or .csv  or .sql

**Comment by Virgula0** [comment]
closed #2
